name: Haxe Project Build(HaxeFlixel)
on:
  push:
    branches:
      - build
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: restore cache libs
        id: restore-libs
        uses: actions/cache@v4.2.0
        with:
          path: /opt/hostedtoolcache/haxe/4.3.1/x64/lib
          key: haxe-library
      
      - name: setup Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.1
      - name: install Lime
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: haxelib install lime
      - name: install OpenFL
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: haxelib install openfl
      - name: install HaxeFlixel
        if: steps.restore-libs.outputs.cache-hit != 'true'
        run: haxelib install flixel
      - name: library check
        run: haxelib list
      # 必要に応じて
      #- name: install flixel-addons etc
        #if: steps.libs-cache.outputs.cache-hit != 'true'
        #run: haxelib run lime setup flixel

      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'

      - name: build
        id: build
        run: haxelib run lime build html5

      - name: upload pages
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./export/html5/bin/
          
      - name: Save Primes
        id: save-libs
        uses: actions/cache/save@v4
        with:
          path: /opt/hostedtoolcache/haxe/4.3.1/x64/lib
          key: haxe-library
      
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
