name: Haxe Project Build(HaxeFlixel)
on:
  push:
    branches:
      - build
jobs:
  build:
    runs_on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@4
        with: 
          repository: '${{ github.repository }}'
