name: Haxe Project Build(HaxeFlixel)
on:
  push:
    branches:
      - build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウトコード
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
