name: Haxe Project Build(HaxeFlixel)
on:
  push:
    branches:
      - build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cache libs
        id: libs-cache
        uses: actions/cache@v4.2.0
        with:
          path: haxelib
          key: haxe-library
      
      - name: setup Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.1
      
      - name: install Lime
        if: steps.libs-cache.outputs.cache-hit != 'true'
        run: haxelib install lime
      - name: install OpenFL
        if: steps.libs-cache.outputs.cache-hit != 'true'
        run: haxelib install openfl
      - name: install HaxeFlixel
        if: steps.libs-cache.outputs.cache-hit != 'true'
        run: haxelib install flixel
      # 必要に応じて
      - name: install flixel-addons etc
        if: steps.libs-cache.outputs.cache-hit != 'true'
        run: haxelib run lime setup flixel

      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'

      - name: build
        run: haxelib run lime build html5

      - name: upload pages
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./export/html5/bin/
  
        
      
