name: Haxe Project Build(HaxeFlixel)
on:
  push:
    branches:
      - build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.3.1
      - name: install Lime
        run: haxelib install lime
      - name: install OpenFL
        run: haxelib install openfl
      - name: install HaxeFlixel
        run: haxelib install flixel
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
